import argparse
import json

with open('BFgen.json') as j:
    lst: list[str] = json.load(j)


def main():
    parser = argparse.ArgumentParser(description="Brainfuck string printer generator.")
    parser.add_argument("script", help="Path to the Brainfuck script to append to")
    parser.add_argument("string", help="String to append to the Branifuck script")

    args = parser.parse_args()

    empty = False
    with open(args.script) as f:
        if f.read() == '':
            empty = True

    with open(args.script, "a") as s:
        s.write(
            f'{'\n[-]' if not empty else ''}[ ==== SCRIPT GENERATED BY BFgen : prints "{args.string}" ==== ]\n'
        )
        add = ''
        for char in args.string.replace("\\n", "\n").replace('\\b', '\b').replace('\\t', '\t').replace('\\r', '\r'):
            add += lst[ord(char)] + ".[-]"
        s.write(add)
        s.write("\n==== END OF BFgen CODE ====\n")


if __name__ == "__main__":
    main()
